### ISSUE TITLE
usb communication

### ISSUE THREAD

**Issue by qweasd7924** [jhaand/blue_riot_blink#1]
Hello. I'm new in RIOT OS, I used your code , it was very useful, but I have question : 
bluepill has microUSB port, witch connected to A11 and A12 pins. Can I setup uart to get message in terminal using microUSB?

**Comment by jhaand** [comment]
Hi,

RIOT-OS does unfortunately not support USB serial for the Blue Pill board. 
As you can see here https://api.riot-os.org/group__boards__common__blxxxpill.html

If you want a board that can do USB serial. I found a handy way to find a board with certain capabilities. Search in the RIOT directory in tests and examples for a test that uses the capability you need. Then search for that test on the Continuous Integration server and see for which board it runs. 
https://ci.riot-os.org/

For example: https://ci.riot-os.org/RIOT-OS/RIOT/14890/18fe16298cd65392307bec3d241f734c3d4bbfdc/output.html
And look for the test "tests/usbus_cdc_acm_stdio" That lists the boards can do USB serial. 

A nice side project would be to make board selection tool for RIOT OS. Just scrape all the capabilities and put it in a matrix. 

Since I can't help you any further, I will close the issue shortly. 

Good luck with RIOT. 

Best Regards,
Jelle
